### ISSUE TITLE
No mention of dataset

### ISSUE THREAD

**Issue by chinmay5** [jaeoh2/CoreML-Traffic-Sign-Classifier#1]
There is very little or no documentation about the dataset you are using. I am trying to use the model but there is no documentation on how to install it or where should I search it for. Can you have some clarification in the documentation for it

**Comment by jaeoh2** [comment]
This is the German traffic sign classifier project for implementing CoreML. SqueezeNet is used as classifier and Keras2 framework used.

http://benchmark.ini.rub.de/?section=gtsrb&subsection=dataset#Downloads
